Update hacker guides 2023
hackupc/guides-page pull request #13
Opened 2023-05-03 13:26 UTC by jmiarons

## What this PR does / why we need it
Update hacker guidelines for HackUPC 2023

## Related Issues

Fixes #

## Some questions

- [ ] I have read the contributing guidelines
- [ ] I abide by this repository Code of Conduct

## Special notes for your reviewer

(optional)

## Additional Notes

Do you want to add anything else? We :heart: to hear your opinions!

2023-05-08 23:13 UTC, ericfib requested changes
Porfis no treguis lo de com arribar al campus. Hi ha coses com lo del hardware que vale tenir-ho només al live pero creiem que les directions i tot val la pena tenirho als dos llocs,

- Carlota i Eric

2023-05-09 09:13 UTC, jmiarons commented
queden molt llargues pero si voleu aixo accepteu la pr

2023-05-09 10:12 UTC, carlotacb approved these changes

2023-05-09 10:16 UTC, ericfib approved these changes

2023-05-09 10:16 UTC, merged